insert into cms.article (id, article_body, article_title, author, changed_by, changed_on, created_by, created_on, excerpt, main_page_img, seo_uri, show_on_main_page) values (39, '<p>Lorem ipsum dolor sit amet, qui an reque dicant soleat, eu probo deseruisse sed. Natum dicta alienum te nam, vivendum dissentiet mei ad. Mea ut dico putant mandamus. Ei duo accusam tincidunt, ut cum impedit euripidis intellegat.</p>
<p>Has populo democritum at! Ius ea putant mediocrem, causae consequuntur pri cu. No nam eius causae, ut dicam munere theophrastus usu! Et molestie quaestio nec. Has quaeque moderatius cu, mei et nibh aliquam consulatu. Nulla nullam numquam vim ne!</p>
<p>Nam quodsi posidonium at. Sit at omittam urbanitas, commune invenire eam ex. Eam ipsum lorem reprehendunt ex. Pro quod omnium similique ne, eam no.</p>', 'Article#1', null, null, null, null, null, null, null, 'article1', null);
insert into cms.article (id, article_body, article_title, author, changed_by, changed_on, created_by, created_on, excerpt, main_page_img, seo_uri, show_on_main_page) values (41, '<p>Lorem ipsum dolor sit amet, vel an possit atomorum abhorreant. Nam no erat percipit, eos ut scripta minimum! Eos dicam commune at, reque everti option ius id! Sint choro in cum. Dolorum adolescens definitionem cu vix? Sea ea facilisis interesset, ei vis magna praesent hendrerit? Albucius molestie salutatus vis id, graeci minimum vituperatoribus an pri.</p>
<p>Officiis sententiae vel ei, te atomorum neglegentur qui! Utroque adolescens adipiscing an vis, mea liber veritus vivendum ad! Ut sonet delicata vim! Eam ea minimum propriae hendrerit, sea quot putant verterem te! Ius quot vidit euismod ei, postea inermis ex sea, ius eu erant adipiscing.</p>', 'Article#2', null, null, null, null, null, null, null, 'article2', null);
insert into cms.article (id, article_body, article_title, author, changed_by, changed_on, created_by, created_on, excerpt, main_page_img, seo_uri, show_on_main_page) values (42, '<p>Lorem ipsum dolor sit amet, odio primis reprimique usu ea, no cibo nostro verear eos. Per nonumy voluptatibus te, tation mollis explicari cu est, sea in dicam facete contentiones. Vel quis inani nusquam ad, ut per alterum voluptaria suscipiantur, sed clita everti consetetur te! Quo cetero sadipscing at?</p>
<p>Ex cum mazim saperet, ius ignota perpetua aliquando in! Ubique hendrerit maiestatis sed at. Euismod liberavisse eu pro, eam etiam ridens ea, mea persius senserit et. Pri te nibh saepe perfecto, te.</p>', 'Article#3', null, null, null, null, null, null, null, 'article3', null);
insert into cms.article (id, article_body, article_title, author, changed_by, changed_on, created_by, created_on, excerpt, main_page_img, seo_uri, show_on_main_page) values (43, '<p>Lorem ipsum dolor sit amet, suas error nam at, tacimates vulputate pro ut. At tacimates scripserit per. Ad facete accusata persecuti sed, an pro magna invidunt dissentias! Appareat lucilius usu ei, nobis consul posidonium sit at! Ne nam nonumes interesset philosophia, vim illud voluptaria an.</p>
<p>Id impetus tibique electram eam? Ne partem nostrum usu. Eu pro velit discere senserit, ea pro elitr admodum omittam. Option equidem repudiandae vix ex, an sed laudem nostro referrentur. Disputando definitiones sed ad, id decore.</p>', 'Article#4', null, null, null, null, null, null, null, 'article4', null);
insert into cms.article (id, article_body, article_title, author, changed_by, changed_on, created_by, created_on, excerpt, main_page_img, seo_uri, show_on_main_page) values (44, '<p>Lorem ipsum dolor sit amet, in iriure petentium pro! Ea pri ullum nominati interpretaris, mei ei dicit tollit. Per ut alia quodsi concludaturque, populo antiopam pri ut. Nam et possit inciderint consectetuer. Ut electram scribentur his, ad omnium qualisque explicari mea.</p>
<p>Singulis incorrupte eu mea, quo te assentior scriptorem. Nec integre lucilius in. Dico vulputate sea no, meis deseruisse interpretaris ei mea. Cum no offendit detraxit, at deserunt iudicabit vis! Ne tantas dissentiunt per.</p>
<p>Iusto constituto concludaturque est an ei.</p>', 'Article#5', null, null, null, null, null, null, null, 'article5', null);
